FROM continuumio/miniconda3:4.10.3-alpine

RUN conda update -y conda
RUN	conda install -y wget
RUN	wget https://data.qiime2.org/distro/core/qiime2-2021.8-py38-linux-conda.yml
ARG env_name=myenv
RUN	conda env create -n ${env_name} --file qiime2-2021.8-py38-linux-conda.yml
ENV CONDA_DEFAULT_ENV ${env_name}
RUN rm qiime2-2021.8-py38-linux-conda.yml
RUN echo "conda activate ${env_name}" >> ~/.bashrc
ENV PATH /opt/conda/envs/${env_name}/bin:$PATH

