
FROM --platform=linux/amd64 ubuntu:18.04 
MAINTAINER DAIKI_KUMAKURA

# utils
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y \ 
           wget \
           tar \
           gcc \
           g++ \
           make \
           zlib1g-dev \
           gzip \
           bzip2 \
           cmake \
           python \
           git \
           unzip \
           cwltool \
           vim \
           sudo \
           --no-install-recommends

# change git config
RUN git config --global http.sslVerify false

# anaconda
RUN set -x && \
    wget https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh && \
    bash Anaconda3-2019.10-Linux-x86_64.sh -b && \
    rm Anaconda3-2019.10-Linux-x86_64.sh

# path setteing
ENV PATH $PATH:/root/anaconda3/bin

# install libraries
WORKDIR /root
RUN pip install --upgrade pip && \
	conda install -c bioconda -y sra-tools && \
    conda install -c bioconda -y trim-galore && \
    conda install -c bioconda -y kallisto


# add permission
WORKDIR /
RUN chmod 777 root

# move to root directory
WORKDIR ../
RUN mkdir /work

