# Base image
FROM kumalpha/debian9-slim-bioconda3:latest

# Installing packages
RUN conda update conda \
  && conda install -c bioconda -y ncbi-genome-download \
  && conda clean --all --yes

